# Helm chart values
harborAdminPassword: "werpoi" #will be moved later
expose:
  type: ingress
  # tls:
  #   enabled: true
  #   certSource: secret
  #   secret:
  #     secretName: harbor-tls
  ingress:
    hosts:
      core: "harbor.kaurislab.ca"
    kubeVersionOverride: "1.34.1"
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/proxy-body-size: "0"