kubeVersion: "1.34.1"

# -- Ingress parameters
ingress:
  enabled: true
  className: "nginx"
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  host: "backstage.kaurislab.ca"
  path: /
  # extraHosts:
  #   - name: "backstage.kauris.local"
  #     path: "/"

backstage:
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80

  # -- Container ports on the Deployment
  containerPorts:
    backend: 7007
  
  extraEnvVars:
    - name: NODE_ENV
      value: production
    # - name: ARGOCD_URL
    #   value: "http://argocd.dev.awsops.kauris.ca"
    - name: APP_CONFIG_backend_baseUrl
      value: 'http://{{ .Values.ingress.host }}'
    - name: CATALOG_LOCATION
      value: "https://github.com/kauris-technology/kodedevops-backstage/blob/main/catalog/catalog-all.yaml"
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    - name: APP_CONFIG_app_baseUrl
      value: 'http://{{ .Values.ingress.host }}'
    - name: 'APP_CONFIG_backend_cors_origin'
      value: 'http://{{ .Values.ingress.host }}`'
  