kubeVersion: "1.34.1"

# -- Ingress parameters
ingress:
  enabled: true
  className: "nginx"
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  host: "backstage.kauris.local"
  path: /
  extraHosts:
    - name: "backstage.kaurislab.ca"
      path: "/"

backstage:
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80

  # -- Container ports on the Deployment
  containerPorts:
    backend: 7007
  
  extraEnvVars:
    - name: NODE_ENV
      value: localdev
    # - name: ARGOCD_URL
    #   value: "http://argocd.dev.awsops.kauris.ca"
    # - name: BASE_URL
    #   value: "backstage.kauris.local"
    - name: CATALOG_LOCATION
      value: "https://github.com/kauris-technology/kodedevops-backstage/blob/main/catalog/catalog-all.yaml"
